name: test-workflow-1
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'redshift/dw-raw/*'
      - 'redshift/dw-risk/*'

permissions:
  contents: write
  pull-requests: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit reporta
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git fetch
          git checkout dev

          git pull origin main
          git push
